### PR TITLE
Response Size added and code refactored.

### PR DESCRIPTION
**Pull request by gopal-mahajan**

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
@gopal-mahajan could you please rebase this with latest 3.5.0 branch changes

**Comment by kailash** [comment]
@gopal-mahajan  Please exclude extra folders from PR
image

**Comment by gopal-mahajan** [comment]
done,

Gopal Mahajan

Software Engineer

Mobile: +918989688484

Email: ***@***.***

India Urban Data Exchange

Indian Institute of Science, Bengaluru

Unleashing the Power of Data for Public Good

<https://iudx.org.in/>

<https://www.linkedin.com/company/iudx/>  <https://twitter.com/IndiaIudx>
<https://www.facebook.com/India-Urban-Data-Exchange-114855197042929>
<https://www.youtube.com/channel/UCK9oI1VtbKnEe7cJIt_eUFA?view_as=subscriber>

**Pull request merged**
