### PR TITLE
external storage

### PR DESCRIPTION
**Pull request by pranavrd**
[surefire-report.pdf](https://github.com/datakaveri/iudx-file-server/files/7956110/surefire-report.pdf)

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by kailash** [comment]
retest this please

**Comment by pranavrd** [comment]
[newman-report.pdf](https://github.com/datakaveri/iudx-file-server/files/7958542/iudx-file-server-api.Copy-2022-01-28-12-17-25-842-0.pdf)

**Comment by kailash** [comment]
retest this please

**Review by kailash — APPROVED** [review]
LGTM

**Pull request merged**
